In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/cafe.csv")
data.shape

(85, 19)

In [ ]:
#Storing some part of the csv file in data1 i.e. breaking the entire file into data 1 and data2
data1=data[0:45]
data1

Store ID                                 Name  ... AFF-Sat AFF-Sun
0      92040                                 Fort  ...     515     385
1      92351          Goregaon East - Oberoi Mall  ...     580     389
2      92413                               Colaba  ...     585     422
3     113991                                Powai  ...     556     373
4     114012     Indira Gandhi Itnl Arpt-T3Gate15  ...     528     413
5     113983     Indira Gandhi Itnl Arpt-T3Gate27  ...     577     448
6     114048            Connaught Place - A Block  ...     591     398
7     114050              Elphinstone Road (West)  ...     568     448
8     116462          Vasant Kunj - Ambience Mall  ...     546     385
9     116465                       Ghatkopar West  ...     593     431
10    116493  Chhatrapati Shivaji DomesticAirport  ...     561     445
11    116571           Malad West - Infiniti Mall  ...     568     373
12    116661                                Saket  ...     575     372
13   1005252                          Nehru Place  ...     515     411
14   1005419                    Greater Kailash 1  ...     589     445
15   1005428              Thane West - Korum Mall  ...     589     386
16   1005505                      Ambience Island  ...     547     361
17   1005583                         Punjabi Bagh  ...     584     404
18   1005753                                 Juhu  ...     538     362
19   1005772            Thane West - Viviana Mall  ...     599     372
20   1005898                            Sector 29  ...     532     438
21   1006014                        Koregaon Park  ...     593     448
22   1006124            Bandra West - Chapel road  ...     522     379
23   1006157                             Hadapsar  ...     509     366
24   1006330                       Santacruz West  ...     568     411
25   1006288                        DLF Cyber Hub  ...     599     433
26   1006375                          Viman Nagar  ...     533     438
27   1006407                          Koramangala  ...     551     435
28   1006406                            Pitampura  ...     441     206
29   1006514                                Aundh  ...     509     408
30   1006632                         Mahadevapura  ...     518     368
31   1006633                   Bandra East - FIFC  ...     557     398
32   1006772                        Church Street  ...     595     449
33   1006738             Malleswaram - Orion Mall  ...     500     361
34   1006711                       Kandivali West  ...     568     410
35   1006993                          Indiranagar  ...     503     368
36   1008346                           Magarpatta  ...     515     425
37   1008480                       Benniganahalli  ...     523     358
38   1008525            Connaught Place - N Block  ...     579     420
39   1006874                                Vashi  ...     501     377
40   1006942                   HUDA Metro Station  ...     591     427
41   1006850                          Kamla Nagar  ...     531     444
42   1006904                        Nariman Point  ...     590     401
43   1007260  Goregaon East- Nirlon KnowledgePark  ...     583     432
44   1006898    Lower Parel - High Street Phoenix  ...     523     365

[45 rows x 19 columns]

In [ ]:
#The remaining csv file is stored in data2
data2=data[45:86]
data2

Store ID                                 Name  ... AFF-Sat AFF-Sun
45   1007494                           Prabhadevi  ...     511     418
46   1007196                            Velachery  ...     549     448
47   1006867         Andheri West - Infiniti Mall  ...     534     361
48   1007217                       Sadashiv Nagar  ...     532     374
49   1008827                             JP Nagar  ...     532     401
50   1006988                    Girgaon Chowpatty  ...     560     434
51   1006888                              Kharadi  ...     550     449
52   1007179            Malleswaram - Mantri Mall  ...     542     402
53   1009093                        Jubilee Hills  ...     511     372
54   1010061                           Whitefield  ...     566     365
55   1007185            Bandra East - The Capital  ...     564     406
56   1007509                           Kukatpally  ...     532     388
57   1008814  Chhatrapati Shivaji Intnl-T2Arrival  ...     539     402
58   1010325                           Kurla West  ...     573     391
59   1010359                         Hi-Tech City  ...     542     407
60   1010110         Andheri West - Four Bunglows  ...     543     388
61   1011451          Vasant Kunj - DLF Promenade  ...     528     363
62   1011564                           Anna Nagar  ...     512     444
63   1011499                         Sohna Road -  ...     511     354
64   1008860                             Madhapur  ...     594     384
65   1009838                              FC Road  ...     545     436
66   1009818                        Banjara Hills  ...     501     442
67   1011563                           Royapettah  ...     534     424
68   1011727                        Subhash Nagar  ...     586     367
69   1011735                             M G Road  ...     580     425
70   1011790  Indira Gandhi International Airport  ...     589     358
71   1009504                            R K Puram  ...     507     423
72   1009882            Bandra West - Link corner  ...     592     407
73   1012363                         Numgambakkam  ...     525     366
74   1013162                             Alwarpet  ...     573     356
75   1011797                        Vikhroli East  ...     589     395
76   1013520                            Hauz Khas  ...     533     362
77   1013509            Malad West - Inorbit Mall  ...     506     389
78   1014117       Lower Parel - Marathon Futurex  ...     567     391
79   1013398                      Vile Parle West  ...     557     358
80   1013682                            Sector 16  ...     574     399
81   1008832  Chhatrapati Shivaji International A  ...     528     376
82   1006943                    Greater Kailash 2  ...     535     415
83   1013443                Bandra East - One BKC  ...     588     354
84   1015306                   One Horizon Center  ...     520     378

[40 rows x 19 columns]

In [ ]:
#if we don't want to create data1 then we can just declare data2 first and then change the data itself.
data=data[0:45]
data

Store ID                                 Name  ... AFF-Sat AFF-Sun
0      92040                                 Fort  ...     515     385
1      92351          Goregaon East - Oberoi Mall  ...     580     389
2      92413                               Colaba  ...     585     422
3     113991                                Powai  ...     556     373
4     114012     Indira Gandhi Itnl Arpt-T3Gate15  ...     528     413
5     113983     Indira Gandhi Itnl Arpt-T3Gate27  ...     577     448
6     114048            Connaught Place - A Block  ...     591     398
7     114050              Elphinstone Road (West)  ...     568     448
8     116462          Vasant Kunj - Ambience Mall  ...     546     385
9     116465                       Ghatkopar West  ...     593     431
10    116493  Chhatrapati Shivaji DomesticAirport  ...     561     445
11    116571           Malad West - Infiniti Mall  ...     568     373
12    116661                                Saket  ...     575     372
13   1005252                          Nehru Place  ...     515     411
14   1005419                    Greater Kailash 1  ...     589     445
15   1005428              Thane West - Korum Mall  ...     589     386
16   1005505                      Ambience Island  ...     547     361
17   1005583                         Punjabi Bagh  ...     584     404
18   1005753                                 Juhu  ...     538     362
19   1005772            Thane West - Viviana Mall  ...     599     372
20   1005898                            Sector 29  ...     532     438
21   1006014                        Koregaon Park  ...     593     448
22   1006124            Bandra West - Chapel road  ...     522     379
23   1006157                             Hadapsar  ...     509     366
24   1006330                       Santacruz West  ...     568     411
25   1006288                        DLF Cyber Hub  ...     599     433
26   1006375                          Viman Nagar  ...     533     438
27   1006407                          Koramangala  ...     551     435
28   1006406                            Pitampura  ...     441     206
29   1006514                                Aundh  ...     509     408
30   1006632                         Mahadevapura  ...     518     368
31   1006633                   Bandra East - FIFC  ...     557     398
32   1006772                        Church Street  ...     595     449
33   1006738             Malleswaram - Orion Mall  ...     500     361
34   1006711                       Kandivali West  ...     568     410
35   1006993                          Indiranagar  ...     503     368
36   1008346                           Magarpatta  ...     515     425
37   1008480                       Benniganahalli  ...     523     358
38   1008525            Connaught Place - N Block  ...     579     420
39   1006874                                Vashi  ...     501     377
40   1006942                   HUDA Metro Station  ...     591     427
41   1006850                          Kamla Nagar  ...     531     444
42   1006904                        Nariman Point  ...     590     401
43   1007260  Goregaon East- Nirlon KnowledgePark  ...     583     432
44   1006898    Lower Parel - High Street Phoenix  ...     523     365

[45 rows x 19 columns]

In [ ]:
data2.to_csv('New.csv',index=None)

In [ ]:
datanew=pd.read_csv('/content/New.csv')
datanew.head()

Store ID                          Name   Brand  ... AFF-Fri AFF-Sat AFF-Sun
0   1007494                    Prabhadevi  Railey  ...     543     511     418
1   1007196                     Velachery  Railey  ...     496     549     448
2   1006867  Andheri West - Infiniti Mall  Railey  ...     548     534     361
3   1007217                Sadashiv Nagar  Railey  ...     504     532     374
4   1008827                      JP Nagar  Railey  ...     489     532     401

[5 rows x 19 columns]

In [ ]:
import numpy as np

In [ ]:
test1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(test1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
test1[0][0]

1

In [ ]:
# Q.1 create a 1 d array of 11 item and find the index value data a[0] and a[0:4].
arr=np.linspace(1,42,11,dtype=int)
arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 42])

In [ ]:
arr[0]

1

In [ ]:
arr[0:4]

array([ 1,  5,  9, 13])

In [ ]:
# Q.2 try to perform conditional operator like <,>  on the array .
arr>23

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[arr>=37 ]

array([37, 42])

In [ ]:
arr[arr<=17]

array([ 1,  5,  9, 13, 17])